title: "Kushagra's Corner"
description: My Portfolio Website
baseurl: ""
url: "https://kuwushagra.github.io"
author: Kushagra Bhagat
githublink: https://github.com/kuwushagra
mailaddress: kushagrabhagat.work@gmail.com
collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title.html
fishlinks: 
  - "/projects/Geepac"
  - "/projects/SimpliFile"
  - "/projects/NeuroSleep"
  - "/projects/Ocean-of-Opportunities"
